# travis - https://docs.travis-ci.com/
language: node_js
node_js:
    - "10"
env:
    - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
    - npm install -g vuepress@1.0.0-alpha.48
script:
  - npm run build
cache:
  directories:
    - "node_modules"
notifications:
  email: false
deploy:
  # pages provider - https://docs.travis-ci.com/user/deployment/pages
  provider: pages
  skip-cleanup: true
  local_dir: src/.vuepress/dist
  github-token: $GITHUB_TOKEN
  repo: wooritech/enumist-docs
  keep-history: true
  fqdn: docs.enumist.com
  on:
    branch: master